config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root  'static_pages#home'
  get   "/help",    to: 'static_pages#help'
  get   "/about",   to: 'static_pages#about'
  get   "/contact",  to: 'static_pages#contact'
  get   "/signup",    to: 'users#new'
  get   "/login",     to: "sessions#new"
  post  "/login",     to: "sessions#create"
  delete "/logout",   to: "sessions#destroy"
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit , :update]
  resources :microposts,          only: [:create, :destroy, :edit]
  resources :relationships,       only: [:create, :destroy]
  get "/microposts", to: "static_pages#home"#15.53
  resources :diaries,             only: [:create, :destroy, :update, :edit]
  get "/diaries", to: "diaries#show"
  get "/index", to: "diaries#index"
  get "/make_diary", to: "diaries#new"

  
  
end

app/models/diary.rb
class Diary < ApplicationRecord
	belongs_to :user
	has_one_attached :image do |attachable|
		attachable.variant :display, resize_to_limit: [500, 500]
	end
	default_scope -> { order(start_time: :desc) }
	validates :user_id, presence: true
	validates :title,	presence: true, length: { maximum: 20 }
	validates :content, presence: true, length: { maximum: 255 }
	validates :start_time, presence: true
	validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
		message: "must be a valid image format" },
size:         { less_than: 5.megabytes,
		message:   "should be less than 5MB" }
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy, :show, :index, :edit]
before_action :correct_user,	only: :destroy
before_action :diary_params , only: [:create, :update]

def show
	if logged_in?
		date = params[:format]
		if date.nil? == false
			search_date = date.to_time
			@diary = current_user.diaries.build(start_time:search_date)
		end
		if date.nil? == true
			search_date=Time.now
			@diary = current_user.diaries.where(start_time:  (search_date.in_time_zone.all_day)).last
				if @diary.nil? == true
					@diary = current_user.diaries.build(start_time:search_date)
				else
					render "diaries/_show", status: :unprocessable_entity
				end

		end
		
		

		#...(Time.now.midnight + 1.day)).last
		if (@diary.nil? == false)
			@title = @diary.title
			@contents = @diary.content
			@start_time = @diary.start_time
		end
		# if (@diary.nil? == true)
		# 	@diary = current_user.diaries.build
		# 	@diary[:start_time] = search_date
		# end
	end

end

def index
	if logged_in?
		diary_id = params[:format]
		if diary_id.nil? == false
			diary = current_user.diaries.find_by(id: diary_id)
			diary_date = diary.start_time
		else
			diary_date = Time.now
		end



		#
		search_dates = []
		10.times do |n|
			search_dates.push(diary_date.ago("#{n}".to_i.years))
		end
		@diary0 = current_user.diaries.where(start_time:  (search_dates[0].in_time_zone.all_day)).last
		@diary1 = current_user.diaries.where(start_time:  (search_dates[1].in_time_zone.all_day)).last
		@diary2 = current_user.diaries.where(start_time:  (search_dates[2].in_time_zone.all_day)).last
		@diary3 = current_user.diaries.where(start_time:  (search_dates[3].in_time_zone.all_day)).last
		@diary4 = current_user.diaries.where(start_time:  (search_dates[4].in_time_zone.all_day)).last
		@diary5 = current_user.diaries.where(start_time:  (search_dates[5].in_time_zone.all_day)).last
		@diary6 = current_user.diaries.where(start_time:  (search_dates[6].in_time_zone.all_day)).last
		@diary7 = current_user.diaries.where(start_time:  (search_dates[7].in_time_zone.all_day)).last
		@diary8 = current_user.diaries.where(start_time:  (search_dates[8].in_time_zone.all_day)).last
		@diary9 = current_user.diaries.where(start_time:  (search_dates[9].in_time_zone.all_day)).last

		
		if @diary0.nil?
			@diary0 = current_user.diaries.build(start_time:diary_date, title: "本日の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary1.nil?
			@diary1 = current_user.diaries.build(start_time:diary_date.ago(1.years), title: "1年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary2.nil?
			@diary2 = current_user.diaries.build(start_time:diary_date.ago(2.years), title: "2年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary3.nil?
			@diary3 = current_user.diaries.build(start_time:diary_date.ago(3.years), title: "3年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary4.nil?
			@diary4 = current_user.diaries.build(start_time:diary_date.ago(4.years), title: "4年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary5.nil?
			@diary5 = current_user.diaries.build(start_time:diary_date.ago(5.years), title: "5年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary6.nil?
			@diary6 = current_user.diaries.build(start_time:diary_date.ago(6.years), title: "6年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary7.nil?
			@diary7 = current_user.diaries.build(start_time:diary_date.ago(7.years), title: "7年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary8.nil?
			@diary8 = current_user.diaries.build(start_time:diary_date.ago(8.years), title: "8年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
		if @diary9.nil?
			@diary9 = current_user.diaries.build(start_time:diary_date.ago(9.years), title: "9年前の日記は未作成です", content: "Diaryより作成可能です。")
		end
	end
end

def new
	if logged_in?
		search_date=Time.now
		
		start_date = params.fetch(:start_date, Date.today).to_date
		# @diaries = current_user.diaries.where(start_time:  start_date.beginning_of_month..start_date.end_of_month)
		@diaries = current_user.diaries.all 
		# #...(Time.now.midnight + 1.day)).last
	end
end

def create
	@diary = current_user.diaries.build(diary_params)
	@diary.image.attach(params[:diary][:image])#list13.64
	if @diary.save
		flash[:success] = "日記保存しました"
		@title = @diary[:title]
		@content = @diary[:content]
		@start_time = @diary[:start_time]
		
		render "diaries/_show", status: :unprocessable_entity
	else
		# render "static_pages/home", status: :unprocessable_entity
	end
end

def update
	@diary = current_user.diaries.find(params[:id])
	if @diary.update(diary_params)
		flash[:success] = "日記更新しました"
		redirect_to @diary
	# 更新に成功した場合を扱う
	else
		render "edit", status: :unprocessable_entity
	end

end

def destroy #list13.56
	@diary.destroy
	flash[:success] = "日記を削除しました"
	if request.referrer.nil?
		redirect_to root_url, status: :see_other
	else
		redirect_to request.referrer, status: :see_other
	end
end

def edit
	diary_id = params[:id]
		@diary = current_user.diaries.find_by(id: diary_id)
end



private

	def diary_params #list13.37参考
		params.require(:diary).permit(:content, :title, :start_time)#list13.64
	end

	def correct_user #list13.55参考
		search_date=Time.now
		@diary = current_user.diaries.where(start_time:  (search_date.in_time_zone.all_day)).last
		redirect_to(root_url, status: :see_other) if @diary.nil?
	end

	def correct_user #list13.55参考
		@diary = current_user.diaries.find_by(id: params[:id])
		redirect_to(root_url, status: :see_other) if @diary.nil?
	end

	def diary_params
		params.require(:diary).permit(:id, :start_time, :title, :content)
	end

	def micropost_params 
		params.require(:micropost).permit(:content, :create_at)#list13.64
	end




end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/diary_helper.rb
module DiaryHelper
end

app/views/diaries/_show.html.erb
<div>
	<table class="table table-bordered" style="table-layout:fixed;width:100%;">

			<thead>
				<tr">
					<th style="word-wrap:break-word;">
					<%= @diary.start_time.strftime("%Y年%m月%d日").to_s  %>の日記
					</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<th style="word-wrap:break-word;">title:<%= @diary.title %></th>
				</tr>
				<tr>
					<th style="word-wrap:break-word;"><%= @diary.content %></th>
				</tr>
			</tbody>	
	</table>
	<%= image_tag @diary.image if @diary.image.attached? %>	

	<% if current_user?(@diary.user) %>
		<%= link_to "日記削除", @diary, data: { "turbo-method": :delete,
                                            turbo_confirm: "削除してよいですか?" } %>
    <% end %>
</div>

app/views/diaries/_test.html.erb
<%= @decade_diaries.each do |diary| %>
	<%= diary %>%
<% end %>%

app/views/diaries/edit.html.erb
<%= form_with(model: @diary) do |f| %>

	<%= f.label :start_time, "作成日" %>
	<%= f.date_field :start_time, class: "form-control" %>

	<%= f.label :title %>
	<%= f.text_field :title, class: "form-control" %>

	<%= f.label :content %>
	<%= f.text_area :content, class: "form-control" %>

	

	<%= f.submit "日記保存", class: "btn btn-primary" %>

	<span class="image">
		<%= f.file_field :image%>
	</span>
	<%= image_tag @diary.image if @diary.image.attached? %>	

<% end %>


</div>

app/views/diaries/index.html.erb
<div>
	<table class="table table-bordered">
			<thead>
				<tr>
					<%# <th style="word-wrap:break-word;"> %>
					<%= @diary0.start_time.strftime("%m月%d日").to_s  %>の日記
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="td-first" rowspan="2"><%= @diary0.start_time.strftime("%y年").to_s %></th>
					<td class="td-second"> title:<%= @diary0.title %></td>
					<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary0.image.attached? %>
							<%= image_tag  @diary0.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>
				</tr>
				<tr>
					<td style="word-wrap:break-word;" ><%= @diary0.content %></td>
				</tr>
				<% if @diary1.nil? == false %>
					<tr>
						<td class="td-first" rowspan="2"><%= @diary1.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary1.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary1.image.attached? %>
							<%= image_tag  @diary1.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>
					</tr>

					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary1.content %></td>
					</tr>
				<% end %>

				<% if @diary2.nil? == false %>
					<tr>
						<td class="td-first" rowspan="2"><%= @diary2.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary2.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary2.image.attached? %>
							<%= image_tag  @diary2.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>						
					</td>
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary2.content %></td>
					</tr>
					
				<% end %>

				<% if @diary3.nil? == false %>
						<tr>
						<td class="td-first" rowspan="2"><%= @diary3.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary3.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary3.image.attached? %>
							<%= image_tag  @diary3.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary3.content %></td>
					</tr>	
				<% end %>

				<% if @diary4.nil? == false %>
					<tr>
						<td class="td-first" rowspan="2"><%= @diary4.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary4.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary4.image.attached? %>
							<%= image_tag  @diary4.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary4.content %></td>
					</tr>
				<% end %>
				<% if @diary5.nil? == false %>
					<tr>
						<td class="td-first" rowspan="2"><%= @diary5.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary5.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary5.image.attached? %>
							<%= image_tag  @diary5.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary5.content %></td>
					</tr>
				<% end %>
				<% if @diary6.nil? == false %>
						<tr>
						<td class="td-first" rowspan="2"><%= @diary6.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary6.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary6.image.attached? %>
							<%= image_tag  @diary6.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>						
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary6.content %></td>
					</tr>
				<% end %>
				<% if @diary7.nil? == false %>
					<tr>
						<td class="td-first" rowspan="2"><%= @diary7.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary7.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary7.image.attached? %>
							<%= image_tag  @diary7.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>						
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary7.content %></td>
					</tr>
				<% end %>

				<% if @diary8.nil? == false %>
					<tr>
						<td class="td-first" rowspan="2"><%= @diary8.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary8.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary8.image.attached? %>
							<%= image_tag  @diary8.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>						
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary8.content %></td>
					</tr>
				<% end %>
				
				<% if @diary9.nil? == false %>
					<tr>
						<td class="td-first" rowspan="2"><%= @diary9.start_time.strftime("%y年").to_s %></th>
						<td class="td-second"> title:<%= @diary9.title %></td>
						<td class="td-third" rowspan="2",rowspan"2" >
						<% if  @diary9.image.attached? %>
							<%= image_tag  @diary9.image ,class: "diary_image"%>
						<% else %>
							<div class="no_image">画像なし</div>
						<% end %>					
					</td>
					</tr>
					<tr>
						<td style="word-wrap:break-word;" colspan="2"><%= @diary9.content %></td>
					</tr>
				<% end %>
			</tbody>	
	</table>

</div>

app/views/diaries/new.html.erb
<%= month_calendar events: @diaries do |start_time, diaries| %>
	<strong><%= start_time.day %></strong>
	<% if diaries != [] %>	
		<%= diaries.each do |diary| %>
			<% if diary.nil? == false %>
			<div>	
				<%= diary.title %>
			</div>
			<%# <%= image_tag diary.image if diary.image.attached? %>
			<div class="calender">
				<ul>
					<li><%= link_to "10年日記", index_path(diary) %></li>
				</ul>
				<ul>
					<li><%= link_to "編集", edit_diary_path(diary) %></li>
					<li><%= link_to "削除", diary, data: { "turbo-method": :delete, turbo_confirm: "本当に日記を削除してよいですか？"} %>
					</li>
				</ul>
			</div>
			<% end %>
			<% break %>
		<% end %>
		<% else %>
		<div><%= link_to "作成", diaries_path(start_time) %></div>

	<% end %>


<% end %>

app/views/diaries/show.html.erb
<%= render "diary/diary_form" %>